### ISSUE TITLE
symbol not found in flat namespace '_kSCDynamicStoreUseSessionKeys'

### ISSUE THREAD

**Issue by tskweres** [everx-labs/ever-sdk-js#573]
Trying to install core and node js on my backend server, and just adding the package and running it produces an error:

Error: dlopen(/Users/deveoloper/dev/repos/app1/node_modules/@eversdk/lib-node/eversdk.node, 0x0001): symbol not found in flat namespace '_kSCDynamicStoreUseSessionKeys'

On a Mac, Node version v20.9.0

Full error:

Error: dlopen(/Users/deveoloper/dev/repos/app1r/node_modules/@eversdk/lib-node/eversdk.node, 0x0001): symbol not found in flat namespace '_kSCDynamicStoreUseSessionKeys'
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1327:18)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at loadAddon (/Users/deveoloper/dev/repos/app1/node_modules/@eversdk/lib-node/index.js:29:16)
    at new BinaryBridge (/Users/deveoloper/dev/repos/app1/node_modules/@eversdk/core/dist/bin.js:58:34)
    at useLibrary (/Users/deveoloper/dev/repos/app1/node_modules/@eversdk/core/dist/bin.js:32:14)
    at Function.useBinaryLibrary (/Users/deveoloper/dev/repos/app1/node_modules/@eversdk/core/dist/client.js:61:30)
    at Object.<anonymous> (/Users/deveoloper/dev/repos/app1/src/modules/ton/ton.service.ts:10:11)

**Comment by segamd2** [comment]
Hello, I'm looking for a user @Hiroaki from bitcointalk. There is a link to cryptonaut.org in his profile. Can you contact me: investhelpnngmailcom.
Sorry for writing here.
